<a href="https://colab.research.google.com/github/Gyunnni/SM12/blob/master/py_modules/py_module_1A_numpy_sm12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy
## concatenate()를 이용한 배열 결합
> [numpy 배열 합치기, concatenate 함수](https://m.blog.naver.com/PostView.nhn?blogId=qbxlvnf11&logNo=221490583222&categoryNo=0&proxyReferer=https%3A%2F%2Fwww.google.com%2F)

In [0]:
import numpy as np

In [0]:
ar1 = np.array(range(1,5)).reshape(2,2)
ar1

array([[1, 2],
       [3, 4]])

In [0]:
ar1.shape

(2, 2)

In [0]:
ar2 = np.array(range(5,11)).reshape(2,3)  # np.array(range(5,11)).reshape(-1,3)
ar2

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [0]:
ar2.shape  # 2 X 3 array

(2, 3)

## concatenate()를 이용한 배열 합치기


- concatenate(array1, array2, axis = 0)
- concatenate(array1, array2, axis = 1)
- concatenate(array1, array2, axis = None)

In [0]:
np.concatenate((ar1,ar1), axis=0).shape

(4, 2)

In [0]:
np.concatenate((ar1,ar1), axis=1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [0]:
np.concatenate((ar1,ar1), axis=None)

array([1, 2, 3, 4, 1, 2, 3, 4])

### Error in concatenation

In [0]:
ar1.shape, ar2.shape

((2, 2), (2, 3))

In [0]:
np.concatenate((ar1,ar2), axis=0)

ValueError: ignored

> ar1의 열의 갯수 == ar2의 열의 갯수

In [0]:
ar1.shape, ar2.shape

((2, 2), (2, 3))

In [0]:
ar2.T.shape

(3, 2)

In [0]:
np.concatenate((ar1,ar2.T), axis=0)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  8],
       [ 6,  9],
       [ 7, 10]])

### concatenate(array1, array2, axis = 1)

In [0]:
np.concatenate((ar1,ar2), axis=1)

array([[ 1,  2,  5,  6,  7],
       [ 3,  4,  8,  9, 10]])



---



---



## numpy 배열 연산: broadcasting
> [파이썬 Numpy 라이브러리 (5) Broadcasting|작성자 예비개발자](https://blog.naver.com/qbxlvnf11/221509303462)

In [0]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b   # elementwise multiplication
# [출처] 파이썬 Numpy 라이브러리 (5) Broadcasting|작성자 예비개발자


array([2., 4., 6.])

In [0]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b   # broadcasted multiplication


array([2., 4., 6.])

> 차원이 다른 두 개의 피연산자를 산술 연산할 때는 원래 연산이 불가능합니다.
하지만, 연산이 가능하도록 배열 b가 브로드캐스팅이 되어 numpy array ([2.0, 2.0, 2.0])으로 확장됩니다.

### 2차원 broadcasting

In [0]:
a = np.array([[ 0.0,  0.0,  0.0],
              [10.0, 10.0, 10.0],
              [20.0, 20.0, 20.0],
              [30.0, 30.0, 30.0]])

b = np.array([1.0, 2.0, 3.0])

a + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [0]:
(a+b).shape

(4, 3)

In [0]:
from numpy import array, newaxis
a = array([0.0, 10.0, 20.0, 30.0])
b = array([1.0, 2.0, 3.0])
c = a[:,newaxis] + b
c


array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [0]:
c.shape

(4, 3)

In [0]:
 a[:,newaxis], b

(array([[ 0.],
        [10.],
        [20.],
        [30.]]), array([1., 2., 3.]))